### ISSUE TITLE
Can't save File with Empty OverflowTable

### ISSUE THREAD

**Issue by jupahe64** [EPD-Libraries/RstbLibrary#1]
Attempting to save a file with an Empty OverflowTable throws an error in this line
since you can't get the Max of an empty collection.
https://github.com/EPD-Libraries/RstbLibrary/blob/3c9b61537cc0deda6fcd36a48063f55b4532988b/src/RstbLibrary/Rstb.cs#L113
I'm pretty sure this can be considered a bug since the OverflowTable isn't used in every game.

**Comment by ArchLeaders** [comment]
Fixed in https://github.com/EPD-Libraries/RstbLibrary/commit/f83cc2f51443ac1780908101ecc2b8a5288dec61
